name: mortgage_magic_demo
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Third-party dependencies!
  flutter_svg: ^2.0.9 # To use SVG images!
  google_fonts: ^6.1.0 # To get the needed fonts!
  carousel_slider: ^4.2.1 # To create the carousel slider!
  smooth_page_indicator: ^1.1.0 # To create the page indicator!
  freezed_annotation: ^2.4.1 # To create the Data classes! Not 100% necessary.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/banners/
    - assets/icons/category/
    - assets/icons/options/
    - assets/icons/navigation/
    - assets/icons/suggestions/
